# Generated by Django 6.0.7 on 2026-09-13 10:38

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('key_hash', models.CharField(db_index=True, max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_report_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'alerts_service',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fingerprint', models.CharField(db_index=True, max_length=64, unique=True)),
                ('service', models.CharField(db_index=True, max_length=64)),
                ('environment', models.CharField(db_index=True, default='production', max_length=32)),
                ('level', models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('fatal', 'Fatal')], db_index=True, default='error', max_length=16)),
                ('kind', models.CharField(choices=[('exception', 'Exception'), ('log', 'Log'), ('dlq', 'DLQ park'), ('monitoring', 'Monitoring'), ('manual', 'Manual')], default='exception', max_length=16)),
                ('title', models.CharField(max_length=255)),
                ('culprit', models.CharField(blank=True, default='', max_length=255)),
                ('exception_class', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('normalised_trace', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('new', 'New'), ('fixed', 'Fixed'), ('regressed', 'Regressed'), ('muted', 'Muted')], db_index=True, default='new', max_length=16)),
                ('note', models.TextField(blank=True, default='')),
                ('count', models.PositiveIntegerField(default=0)),
                ('count_since_fix', models.PositiveIntegerField(default=0)),
                ('first_seen', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_seen', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('fixed_in_version', models.CharField(blank=True, default='', max_length=64)),
                ('fixed_in_sha', models.CharField(blank=True, default='', max_length=64)),
                ('fixed_at', models.DateTimeField(blank=True, null=True)),
                ('regressed_at', models.DateTimeField(blank=True, null=True)),
                ('muted_until', models.DateTimeField(blank=True, null=True)),
                ('sentry_event_id', models.CharField(blank=True, default='', max_length=64)),
            ],
            options={
                'db_table': 'alerts_issue',
                'ordering': ('-last_seen',),
                'indexes': [models.Index(fields=['service', 'status', '-last_seen'], name='alerts_issue_triage'), models.Index(fields=['status', 'level'], name='alerts_issue_open')],
            },
        ),
        migrations.CreateModel(
            name='ErrorEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('received_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('service', models.CharField(db_index=True, max_length=64)),
                ('environment', models.CharField(default='production', max_length=32)),
                ('release', models.CharField(blank=True, default='', max_length=64)),
                ('level', models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('fatal', 'Fatal')], default='error', max_length=16)),
                ('kind', models.CharField(choices=[('exception', 'Exception'), ('log', 'Log'), ('dlq', 'DLQ park'), ('monitoring', 'Monitoring'), ('manual', 'Manual')], default='exception', max_length=16)),
                ('message', models.TextField(blank=True, default='')),
                ('trace', models.TextField(blank=True, default='')),
                ('context', models.JSONField(blank=True, default=dict)),
                ('request_path', models.CharField(blank=True, default='', max_length=512)),
                ('trace_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('user_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('occurrences', models.PositiveIntegerField(default=1)),
                ('sentry_event_id', models.CharField(blank=True, default='', max_length=64)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='alerts.issue')),
            ],
            options={
                'db_table': 'alerts_error_event',
                'ordering': ('-received_at',),
                'indexes': [models.Index(fields=['issue', '-received_at'], name='alerts_event_by_issue')],
            },
        ),
    ]
